use_frameworks!

platform :ios, '8.0'

target 'YACOBasicFoundation_Example' do
  pod 'YACOBasicFoundation', :path => '../'

  target 'YACOBasicFoundation_Tests' do
    inherit! :search_paths

    
  end
end
